# Generated by Django 4.1 on 2022-08-29 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('embarked', models.CharField(choices=[('C', 'Cherbourg'), ('Q', 'Queenstown'), ('S', 'Southampton')], max_length=1)),
                ('pclass', models.CharField(choices=[('1', 'First class'), ('2', 'Second class'), ('3', 'Third class')], max_length=1)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('sibsp', models.IntegerField()),
                ('parch', models.IntegerField()),
                ('fare', models.IntegerField()),
                ('prediction', models.IntegerField(blank=True)),
            ],
        ),
    ]
