POST http://localhost:8000/
content-type: application/json

{
    "test": "test attribute"
}

###
POST http://localhost:8000/
content-type: application/json

{
    "age": 10,
    "embarked": "C",
    "pclass": "1",
    "sex": "male",
    "sibsp": 0,
    "parch": 2,
    "fare": 100
}

###
GET http://localhost:8000

###
PUT http://localhost:8000

